library(dplyr)
library(apply)
setwd("/Users/North_Point/Dropbox/MOOC/Data_Science/Getting_and_Cleaning_Data/Quiz/week4")
if(!file.exists("./data")){
        dir.create("./data")
}
download.file("https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2Fss06hid.csv", "./data/data_1.csv", method = "curl")
data_1 = read.csv("./data/data_1.csv")
head(data_1)
data_1_names = names(data_1)
data_1_names = tolower(data_1_names)
splitnames_1 = strsplit(data_1_names, "wgtp")
splitnames_1[[123]]

download.file("https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FGDP.csv", "./data/data_2.csv", method = "curl")
data_2 = read.csv("./data/data_2.csv", skip = 4)
data_2 = select(data_2, c(1,2,3,4,5))
data_2 = filter(data_2, X.1 %in% seq(1,190,1))
head(data_2)
data.2.gdp = as.character(data_2$X.4)
head(data.2.gdp)
data.2.gdp = as.numeric(gsub(",","",data.2.gdp,))
head(data.2.gdp)
mean(data.2.gdp, na.rm = TRUE)
str(data.2.gdp)
tail(data.2.gdp)
names(data_2) = c("ID", "Ranking", "X.2", "countryNames", "GDP")
grep("^United", data_2$countryNames)


download.file("https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2FEDSTATS_Country.csv", "./data/data_3.csv", method = "curl")
data_3 = read.csv("./data/data_3.csv")
head(data_3)
names(data_3)
data_3 = select(data_3, CountryCode, Special.Notes) 
data_4 = merge(data_2, data_3, by.x = "ID", by.y = "CountryCode")
head(data_4)
data_4.sn = data_4$Special.Notes
grep("^Fiscal year end: June", data_4.sn, value = TRUE)

library(quantmod)
amzn = getSymbols("AMZN",auto.assign=FALSE)
sampleTimes = data.frame(index(amzn))
head(sampleTimes)
str(sampleTimes)
wk = weekdays(sampleTimes)
library(lubridate)
install.packages("lubridate")
start = ymd(20120101)
end = ymd(20121231)
sub = filter(sampleTimes, index.amzn. >= start)
str(sub)
sub = filter(sub, index.amzn. <= end)
str(sub)
sub.wk = mutate(sub, wk = weekdays(index.amzn.))
head(sub.wk)
sub.wk = filter(sub.wk, wk == "Monday")
str(sub.wk)
